### PR TITLE
Another stab at #15

### PR DESCRIPTION
**Pull request by LeaVerou**
Alternative to #18 

Fixed the issue with the array children a slightly different way, which also allows `map()` to accept an array

Still untested 😅

### CODE REVIEW

**Comment by adamjanicki2** [comment]
Want me to add the tiny test suite to this PR, or merge your changes to `children` and `map` into my branch?

**Comment by adamjanicki2** [comment]
Overall, I like the idea of having the internal `_map` accept either a single node or an array of nodes, I think it's certainly cleaner than my solution

**Comment by LeaVerou** [comment]
> Want me to add the tiny test suite to this PR, or merge your changes to `children` and `map` into my branch?

Up to you!

**Comment by LeaVerou** [comment]
Just please test that it actually works before merging 😅

**Comment by adamjanicki2** [comment]
Sounds good, I will port your changes into my branch, and get one final review before merging, as well as ensuring that tests work

**Comment by LeaVerou** [comment]
Nit: Please fix indentation

**Comment by adamjanicki2** [comment]
> Nit: Please fix indentation

Done

**Pull request merged**
