### PR TITLE
transform option 2

### PR DESCRIPTION
**Pull request by adamjanicki2**
Second option for #20

### CODE REVIEW

**Comment by adamjanicki2** [comment]
Main difference is using
```js
if (transformedNode !== undefined) {
	Object.assign(node, transformedNode);
}
```
instead of 
```
node = transformedNode !== undefined ? transformedNode : node;
```

**Review by LeaVerou — CHANGES_REQUESTED** [review]
> Main difference is using
> 
> ```js
> if (transformedNode !== undefined) {
> 	Object.assign(node, transformedNode);
> }
> ```
> 
> instead of
> 
> ```js
> node = transformedNode !== undefined ? transformedNode : node;
> ```

Could you elaborate on the rationale? These are not at all equivalent. If your callback returns a different type (as often happens with these transformations), with the `Object.assign()` approach you will end up with a node that doesn't conform to any type and has a union of all properties. The latter is a more correct approach. The `Object.assign()` approach *could* work, and can be useful when you need to maintain object references, but you'd first need to delete all existing properties. The advantage of this is that references to the old object outside our code will continue to work. Mavo does this in `src/data.js` IIRC, to update data when it changes. But in this case, I don't think it's a good plan, since the callback changes the objects so dramatically that it's probably *better* to break these refereences.

This should have been caught by the tests, but there is no test where the callback returns a different type.

Btw we could have had this discussion in one PR, and we could have iterated there. Sending two PRs for a minor difference is too heavyweight (primarily for you, for me it's the same!).

**Comment by adamjanicki2** [comment]
> Could you elaborate on the rationale?

I didn't have a rationale for this choice besides it being fewer lines, so I wanted to ask. On the same page about going with the other choice!

> This should have been caught by the tests, but there is no test where the callback returns a different type.

I will add some tests for this

> Btw we could have had this discussion in one PR, and we could have iterated there. Sending two PRs for a minor difference is too heavyweight (primarily for you, for me it's the same!).

Noted, will do this going forward

**Comment by adamjanicki2** [comment]
Closing this and moving conversation to #23

**Pull request closed without merging**
