### PR TITLE
delete transformations from serialize

### PR DESCRIPTION
**Pull request by adamjanicki2**
Addresses #16

### CODE REVIEW

**Comment by LeaVerou** [comment]
Cool, but we need to fix #15 first otherwise we'd have *no* way of doing what these transformations are currently doing! I'll leave this open until we do.

**Comment by adamjanicki2** [comment]
> Cool, but we need to fix #15 first otherwise we'd have _no_ way of doing what these transformations are currently doing! I'll leave this open until we do.

Got it, the map PR is #18

**Comment by adamjanicki2** [comment]
@LeaVerou I rebased with main, so this should be ready for review now

**Review by LeaVerou — APPROVED** [review]
Approved but we may want to deal with https://github.com/mavoweb/vastly/issues/21 first

**Pull request merged**
